---
title: "Project 325"
output: html_document
date: "2023-10-20"
---

R_moment_4 prediction 

```{r}
data <- read.csv("data-train.csv")
hist(data$R_moment_4)
hist(log(data$R_moment_4))#log transformation of Rmoment4
hist(data$R_moment_4^0.5)
hist(data$R_moment_4^-2)
hist(data$R_moment_4^-3)

#histogram of predictors
hist(data$St)
hist(data$Re)
hist(data$Fr)
data$lSt<-log(data$St)
# Create a categorical variable that categorize Fr into subcritical, critical, and supercritical
data$Fr[data$Fr == "Inf"] <- 999
data$cfr <- cut(data$Fr, breaks = c(0,0.99,1.001,1001),labels=c(1,2,3) )
data$cfr<-as.numeric(data$cfr)
hist(data$cfr)
#logit transformation 
data$lgfr=1/(1+exp(-data$Fr))
data$lgfr
hist(data$lgfr)
#scatterplots
plot(data$lSt,data$R_moment4, xlab="lSt", ylab="R_moment4")
pairs(r4~ lSt+Re+cfr,data=data)#scatterplot of paired predictors and response variable 
plot(data$lSt,data$R_moment_4)
plot(data$St,data$R_moment_4)



```

```{r}
#linear model by ordinary least square  
lm.1<-lm(r4~log(St)+Re+cfr,data=data)
summary(lm.1)
```
```{r}
#Ridge regression 
library(glmnet)
grid=10^seq(10,-2,length=100)
Name=c("lSt", "Re","cfr")
train.x <- subset(data, select = Name)
train.y<-subset(data, select="r4")
train.x<-as.matrix(train.x)
train.y <- as.matrix(train.y)
test.x<-as.matrix(read.csv("data-test.csv"))
set.seed(1)
ridge.m4=cv.glmnet(x=train.x,y=train.y,alpha =0)
bestlam=ridge.m4$lambda.min
rid.pred<-predict(ridge.m4, s=bestlam,  newx= test.x)
```


```{r}
#Examine interaction effects
interaction.plot(x.factor = data$St,trace.factor = data$Re,response = data$r4)
interaction.plot(x.factor = data$St,trace.factor = data$cfr,response = data$r4)
interaction.plot(x.factor = data$Re,trace.factor = data$cfr,response = data$r4)
#add interaction terms 
lm.2<-lm(r4~lSt+Re+Re*cfr,data=data)

summary(lm.2)

```

```{r}
#Dummy variable
# Create categorical variables that categorize Fr into subcritical, critical, and supercritical
install.packages("dplyr")
library(dplyr)
breakpoints <- c(0,0.99,1.001,1001)
data <- data %>%
  mutate(critical_cate = cut(data$Fr, breaks = breakpoints, labels = c("sub", "cri","sup")))
data$critical_cate
data <- data %>%
  mutate(Sub = ifelse(critical_cate == "sub", 1, 0))
#perform regression 
dummy1 <- lm(data$r4 ~ log(St)+Re+Sub, data = data)
summary(dummy1)

```


```{r}
#natural spline
install.packages("splines")
library("splines")

gam1=lm(r4~ns(lSt)+ns(Re) +ns(cfr),data=data)
summary(gam1)

gam2<-lm(r4~ns(lSt)+ns(Re)+Sub, data=data)
summary(gam2)
```

```{r}
#perform loocv to select model:
set.seed(22)
library(boot)

lm.1=glm(r4~lSt+Re+cfr,data=data)
  ridge.m4=cv.glmnet(x=train.x,y=train.y,alpha =0)
  lm.2=glm(r4~lSt+Re+Re*cfr,data=data)
  dummy1 =glm(r4 ~ lSt+Re+Sub, data = data)
  gamcfr<-glm(r4~ns(lSt)+ns(Re) +ns(cfr),data=data)
  gamdum<-glm(r4~ns(lSt)+ns(Re)+Sub, data=data)
results <- list()  # Store LOOCV results
mname<-list()#store model names
results[1]<-cv.glm(data=data, lm.1)$delta[1]
mname[1]<-"linear ols with lst, re, cfr"
results[2]<- min(ridge.m4$cvm)
mname[2]<-"ridge regression with lst, re cfr"
results[3]<-cv.glm(data=data, lm.2)$delta[1]
mname[3]<-"ols with lst, re cfr, and interaction re*cfr"
results[4]<-cv.glm(data=data, dummy1)$delta[1]
mname[4]<-"ols regression with lst, re and dummy variable sub"
results[5]<-cv.glm(data, gamcfr)$delta[1]
mname[5]<-"Generalized additive model with natural splines of lst, re and cfr"
results[6]<-cv.glm(data, gamdum)$delta[1]
mname[6]<-"Generalized additive model with natural splines(ns) of lst, ns of re and dummy variable sub "
results
for (i in seq_along(results)) {
  cat("Model Name:", mname[[i]], "\n")
  cat("cv error:", results[[i]], "\n\n")
}
  
```
```{r}
data.test<-read.csv("data-test.csv")
predict.r4<-predict(lm.2, data=data.test)
```

R_moment_2 prediction 

```{r}
#histogram of moment2
hist(data$R_moment_2)
hist(data$R_moment_2^-2)
hist(log(data$R_moment_2))
#paired scatterplot
pairs(r2~ lSt+Re+cfr,data=data)
plot(data$lSt, data$r2)
#log tranformation of moment2
data$r2<-log(data$R_moment_2)

#linear model least square 
lm.3<-lm(r2~lSt+Re+cfr,data=data)
lm.sub<-lm(r2~lSt+Re+Sub, data=data)
summary(lm.sub)
summary(lm.3)
predict(lm.3, data=data)
predict(lm.sub, data=data)
1.418403  /2
#Ridge regression 
library(glmnet)
grid=10^seq(10,-2,length=100)
Name=c("St", "Re","cfr")
train.x <- subset(data, select = Name)
train.y2<-subset(data, select="r2")
train.x<-as.matrix(train.x)
train.y2 <- as.matrix(train.y2)
test.x<-as.matrix(read.csv("data-test.csv"))
set.seed(1)
ridge.m2=cv.glmnet(x=train.x,y=train.y2,alpha =0)
bestlam=ridge.m2$lambda.min
rid.pred<-predict(ridge.m2, s=bestlam,  newx= test.x)


```


```{r}
#Examine interaction effects
interaction.plot(x.factor = data$St,trace.factor = data$Re,response = data$r2)
interaction.plot(x.factor = data$St,trace.factor = data$cfr,response = data$r2)
interaction.plot(x.factor = data$Re,trace.factor = data$cfr,response = data$r2)

#add interaction terms 
lm.4<-lm(r2~lSt+Re+Re*cfr,data=data)
summary(lm.4)
lm.5<-lm(r2~lSt+Re+Re*Sub, data=data)

summary(lm.5)
anova(lm.3,lm.4)
```
```{r}
#dummy variable 
dum2 <- lm(data$r2 ~ lSt+Re+Sub, data = data)
summary(dum2)

```

```{r}
#natural spline
gam1=lm(r2~ns(lSt)+ns(Re) +ns(cfr),data=data)
summary(gam1)
gam2<-lm(r2~ns(lSt)+ns(Re)+Sub, data=data)
summary(gam2)
```

```{r}

#perform loocv to select model:
set.seed(22)
library(boot)

lm.3=glm(r2~log(St)+Re+cfr,data=data)
ridge.m2=cv.glmnet(x=train.x,y=train.y2,alpha =0)
lm.4<-glm(r2~lSt+Re+cfr+Re*cfr,data=data)
data
dum2 <- glm(r2 ~ lSt+Re+Sub, data = data)
gamcfr<-glm(r2~ns(lSt)+ns(Re) +ns(cfr),data=data)
gamdum<-glm(r2~ns(lSt)+ns(Re)+Sub, data=data)  
results <- list()  # Store LOOCV results
results[1]<-cv.glm(data=data, lm.3)$delta[1]
results[2]<- min(ridge.m2$cvm)
results[3]<-cv.glm(data=data, lm.4)$delta[1]
results[4]<-cv.glm(data=data, dum2)$delta[1]
results[5]<-cv.glm(data, gamcfr)$delta[1]
results[6]<-cv.glm(data, gamdum)$delta[1]
results
mname[1]<-"linear ols with lst, re, cfr"
mname[2]<-"ridge regression with lst, re cfr"
mname[3]<-"ols with lst, re cfr, and interaction re*cfr"
mname[4]<-"ols regression with lst, re, and dummy variable sub"
mname[5]<-"Generalized additive model with natural splines of lst, re and cfr"
mname[6]<-"Generalized additive model with natural splines(ns) of lst, ns of re and dummy variable sub "
for (i in seq_along(results)) {
  cat("Model Name:", mname[[i]], "\n")
  cat("cv error:", results[[i]], "\n\n")
}

```


```{r}

#Prediction 
data.test<-read.csv("data-test.csv")
data.test
data.test$Fr[data.test$Fr == "Inf"] <- 999
data.test$cfr <- cut(data.test$Fr, breaks = c(0,0.99,1.001,1001),labels=c(1,2,3) )
data.test$cfr<-as.numeric(data.test$cfr)
data.test$lSt<-log(data.test$St)
predict.r2<-predict(lm.4, data=data.test)
exp(predict.r2)
```


```{r}
data$R_moment_2
```
```{r}
data.test <- read.csv("data-train.csv")
# Create a categorical variable that categorize Fr into subcritical, critical, and supercritical
data.test$Fr[data$Fr == "Inf"] <- 999
data.test$cfr <- cut(data$Fr, breaks = c(0,0.99,1.001,1001),labels=c(1,2,3) )
data.test$cfr<-as.numeric(data$cfr)
data.test$lSt<-log(data$St)
lm.4<-glm(r2~lSt+Re+cfr+Re*cfr,data=data)

#Prediction 
data.test2<-read.csv("data-test.csv")
predict.r2<-predict(lm.4, newdata=data.test2)
exp(predict.r2)

```

